name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-static-i18n
      
      - name: Build MkDocs
        run: |
          # Check if CNAME exists, if not, use GitHub Pages URL
          if [ ! -f CNAME ]; then
            echo "No custom domain, updating site_url for GitHub Pages"
            sed -i 's|site_url: https://docs.picsew.app|site_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/|g' mkdocs.yml
          else
            echo "Custom domain found: $(cat CNAME)"
            # Keep the existing site_url for custom domain
          fi
          mkdocs build
          # Copy CNAME to site directory if it exists
          if [ -f CNAME ]; then
            cp CNAME site/
            echo "CNAME file copied to site directory"
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4